### ISSUE TITLE
missing document.currency

### ISSUE THREAD

**Issue by freyfogle** [quaderno/quaderno-templates#10]
It seems there is a variable called `document.currency`

It is not documented here: https://github.com/quaderno/quaderno-templates/wiki/Variables

Perhaps you can add it and any others that are missing, I wasted a long time looking for it. 

Thanks

**Comment by dormi** [comment]
Added a few missing variables for the documents drop:

`exchange_rate, amount_paid, amount_due, tax_id, country, type, currency, auto?, reverse_charged?, processor_id, processor`

Thanks for the heads up 👍
