### ISSUE TITLE
Use "custom_metadata" in template

### ISSUE THREAD

**Issue by laurapaumier** [quaderno/quaderno-templates#11]
In the API, I can add "custom_metadata" to my invoice. I wonder if it's possible to add this additional information in the template ?

**Comment by dormi** [comment]
Yes, you can.

If a method name in the template is not in the list of known methods, it will be searched in the invoice `custom_metadata`.

The list of known methods is:  https://github.com/quaderno/quaderno-templates/wiki/Variables#document

**Comment by laurapaumier** [comment]
Super ! It works fine. Thank you very much for your response.
