### ISSUE TITLE
labels.paid not recognised

### ISSUE THREAD

**Issue by craigscott-crascit** [quaderno/quaderno-templates#4]
The last commit on master (44399a3b2bbc75764d6b2550d97d11de1d0554c6) changes the paid label from `paid_stamp` to `labels.paid`. If you use the updated value on Quaderno right now, you get a blank string where you used to get the correct label before. Basically, it looks like `labels.paid` is not recognised as a valid label. Is this an error in the template or is Quaderno itself at fault?

**Comment by polimorfico** [comment]
Hi Craig! `labels.paid` is correct. Just checked your Quaderno account and the translation was not saved successfully on Settings > Translations > English. Just fixed that and now you can use that attribute with no issues. Sorry for all inconveniences.

**Comment by craigscott-crascit** [comment]
Thanks, I see that there's a broader issue with some labels. Looks like a number of labels got added later and all languages just got the English value. I'll follow up through Quaderno support instead rather than here since it is now an account issue.
